apiVersion: v1
kind: Service
metadata:
  name: kubernetes-client-svc
  labels:
    app: kubernetes-client
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: kubernetes-client