apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-client-deploy
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: kubernetes-client
    spec:
      containers:
      - name: kubernetes-client-pod
        image: systelab/kubernetes-client:latest
